##################################################################################
#
# Olza Logistic's Pickup Points API client
#
# @author    Marcin Orlowski <marcin.orlowski (#) develart (.) cz>
# @copyright 2022-2023 DevelArt
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/develart-projects/pickup-points-api-client/
#
##################################################################################
#
# Runs markdownlint on all *.md files
#

name: "Markdown Lint"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: "Checkout repository..."
        uses: actions/checkout@v3


      # https://github.com/marketplace/actions/my-markdown-linter
      - name: "Running markdown linter..."
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          exclude: vendor
          config_file: .markdownlint.yaml.dist
