##################################################################################
#
# Olza Logistic's Pickup Points API client
#
# @author    Marcin Orlowski <marcin.orlowski (#) develart (.) cz>
# @copyright 2022-2024 DevelArt
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/develart-projects/pickup-points-api-client/
#
##################################################################################
#
# Runs unit tests
#

name: "Unit Tests"

on:
  push:
    branches:
    - "master"
  pull_request:
    branches:
    - "master"
    - "dev"

jobs:
  tests:
    strategy:
      # do not stop the workflow if a single run failed
      fail-fast: false
      matrix:
        # quotes are needed it is treated as a number and zero at decimal part is gone at runtime
        php: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]

    runs-on: ubuntu-22.04

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: "Checkout repository…"
        uses: actions/checkout@v3

      - name: "Running PHPUnit…"
        shell: bash
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          /usr/local/bin/composer install --dev
          /usr/local/bin/composer test
