##################################################################################
#
# Olza Logistic's Pickup Points API client
#
# @author    Marcin Orlowski <marcin.orlowski (#) develart (.) cz>
# @copyright 2022-2023 DevelArt
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/develart-projects/pickup-points-api-client/
#
##################################################################################
#
# Runs unit tests
#

name: "Unit Tests"

on:
  push:
    branches:
    - "master"
  pull_request:
    branches:
    - "master"
    - "dev"

jobs:
  tests:
    strategy:
      # do not stop the workflow if single run failed
      fail-fast: false
      matrix:
        # quotes are needed it is treated as a number and zero at decimal part is gone at runtime
        php: ["7.4", "8.0", "8.1"]

    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: "Checkout repository..."
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/composer-php-actions
      - name: "Installing dependencies..."
        uses: php-actions/composer@v6
        with:
          version: 2
          php_version: "${{ matrix.php }}"
          dev: yes

      - name: "Running PHPUnit..."
        shell: bash
        run: "/usr/bin/env php composer test"
